### PR TITLE
Fix Typos in README.md]

### PR DESCRIPTION
**Pull request by rahul0x00**
I found few typos in the README.md

1. "privacy-focus" should be corrected to "privacy-focused."
2. "Insomnia is a fork of Kong/insomnia at 2023.5.8" should be corrected to "Insomnia is a fork of Kong/Insomnia at 2023.5.8."
3. "If you have any feature request or encountered any bug..." should be corrected to "If you have any feature requests or encountered any bugs..."
4. "Insomnium is available for Mac, Windows, Ubuntu, Debian, CentOS, Fedora and can be downloaded here." should be corrected to "Insomnium is available for Mac, Windows, Ubuntu, Debian, CentOS, Fedora, and can be downloaded here."
5. "Development on Insomnium can be done on Mac, Windows, or Linux as long as you have Node.js and Git." should be corrected to "Development on Insomnium can be done on Mac, Windows, or Linux as long as you have Node.js and Git installed."

### CODE REVIEW

**Comment by rahul0x00** [comment]
I didn't create a separate issue for these minor changes, I wanted to improve the documentation's clarity and correctness proactively.

**Comment by archywillhe** [comment]
sorry I accidentally closed it; looks like it's deleted now

**Comment by rahul0x00** [comment]
@archywillhe no issues, i restored the branch

**Comment by archywillhe** [comment]
it's alright. i just fixed the first typo myself; other than i will keep the rest as is

**Comment by rahul0x00** [comment]
sure thing

**Comment by rahul0x00** [comment]
Let me know if you want any changes

**Pull request closed without merging**
