### PR TITLE
Enhanced the LICENSE section in README.md

### PR DESCRIPTION
**Pull request by shelar1423**
before :
image

after:
image

### CODE REVIEW

**Comment by shelar1423** [comment]
@archywillhe  kindly have a review

**Comment by shelar1423** [comment]
@archywillhe

**Comment by shelar1423** [comment]
@archywillhe

**Comment by shelar1423** [comment]
@archywillhe

**Comment by archywillhe** [comment]
sorry. closing for being unconstructive;

**Pull request closed without merging**
